import { useState } from "react";
import api from "../services/api";
import useFetch from "../hooks/useFetch";
import { messageOf } from "../utils/apiHelpers";
import Modal from "./Modal";

export default function CrudPage({ type, title, fields, columns }) {
  const { data, loading, error, reload } = useFetch(`/${type}`); const [editing, setEditing] = useState(null); const [form, setForm] = useState({}); const [notice, setNotice] = useState("");
  const open = (item = null) => { setEditing(item || {}); setForm(item || {}); setNotice(""); };
  const save = async (event) => { event.preventDefault(); try { const body = { ...form }; delete body._id; delete body.createdAt; delete body.updatedAt; if (editing?._id) await api.put(`/${type}/${editing._id}`, body); else await api.post(`/${type}`, body); setEditing(null); reload(); } catch (requestError) { setNotice(messageOf(requestError)); } };
  const remove = async (id) => { if (!window.confirm("Delete this item?")) return; try { await api.delete(`/${type}/${id}`); reload(); } catch (requestError) { setNotice(messageOf(requestError)); } };
  const complete = async (id) => { try { await api.patch(`/tasks/${id}/complete`); reload(); } catch (requestError) { setNotice(messageOf(requestError)); } };
  return <><div className="toolbar"><div><h2>{title}</h2><p className="muted">Keep your study information organized.</p></div><button className="primary" onClick={() => open()}>Add {title.slice(0, -1)}</button></div>{notice && <div className="error">{notice}</div>}{loading ? <div className="card empty">Loading...</div> : error ? <div className="error">{error}</div> : <div className="card table-wrap">{data.length ? <table className="table"><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}<th>Actions</th></tr></thead><tbody>{data.map((item) => <tr key={item._id}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(item) : item[column.key] || "-"}</td>)}<td><div className="actions"><button className="secondary" onClick={() => open(item)}>Edit</button>{type === "tasks" && !item.completed && <button className="secondary" onClick={() => complete(item._id)}>Complete</button>}<button className="danger" onClick={() => remove(item._id)}>Delete</button></div></td></tr>)}</tbody></table> : <div className="empty">No {title.toLowerCase()} yet.</div>}</div>}{editing !== null && <Modal title={`${editing._id ? "Edit" : "Add"} ${title.slice(0, -1)}`} onClose={() => setEditing(null)}><form className="form" onSubmit={save}>{fields.map((field) => <label className="field" key={field.name}>{field.label}{field.options ? <select required={field.required} value={form[field.name] || ""} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })}><option value="">Select...</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.required} type={field.type || "text"} value={form[field.name] || ""} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })} />}</label>)}{notice && <div className="error">{notice}</div>}<button className="primary">Save</button></form></Modal>}</>;
}