import { useState } from "react";
import api from "../services/api";
import useFetch from "../hooks/useFetch";
import { messageOf } from "../utils/apiHelpers";

export default function Attendance() {
  const { data, loading, error, reload } = useFetch("/attendance"); const subjects = useFetch("/subjects"); const [form, setForm] = useState({ subjectId: "", date: new Date().toISOString().slice(0, 10), status: "Present" });
  const save = async (event) => { event.preventDefault(); try { await api.post("/attendance", form); reload(); } catch (requestError) { alert(messageOf(requestError)); } };
  return <><section className="card"><div className="section-title"><h2>Mark attendance</h2></div><form className="form" onSubmit={save}><label className="field">Subject<select required value={form.subjectId} onChange={(event) => setForm({ ...form, subjectId: event.target.value })}><option value="">Select subject</option>{subjects.data.map((subject) => <option value={subject._id} key={subject._id}>{subject.name}</option>)}</select></label><label className="field">Date<input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label className="field">Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option>Present</option><option>Absent</option></select></label><button className="primary">Save attendance</button></form></section><section className="card" style={{ marginTop: 20 }}><h2>History</h2>{loading ? <div className="empty">Loading...</div> : error ? <div className="error">{error}</div> : <table className="table"><thead><tr><th>Date</th><th>Subject</th><th>Status</th></tr></thead><tbody>{data.map((attendance) => <tr key={attendance._id}><td>{new Date(attendance.date).toLocaleDateString()}</td><td>{attendance.subjectId?.name || attendance.subjectName || "Subject"}</td><td><span className={`badge ${attendance.status === "Present" ? "done" : "high"}`}>{attendance.status}</span></td></tr>)}</tbody></table>}</section></>;
}