import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../services/api";
import { getData, messageOf } from "../utils/apiHelpers";

export default function Dashboard() {
  const [summary, setSummary] = useState(null); const [attendance, setAttendance] = useState({ data: [], percentage: 0 }); const [subjects, setSubjects] = useState([]); const [selectedSubject, setSelectedSubject] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.get("/dashboard"), api.get("/attendance/stats"), api.get("/subjects")]).then(([dashboard, stats, subjectResponse]) => { setSummary(getData(dashboard)); setAttendance(stats.data || { data: [], percentage: 0 }); setSubjects(getData(subjectResponse) || []); }).catch((requestError) => setError(messageOf(requestError))); }, []);
  if (error) return <div className="error">{error}</div>; if (!summary) return <div className="card empty">Loading dashboard...</div>;
  const overall = attendance.percentage ?? summary.overallAttendance ?? 0; const selected = (attendance.data || []).find((subject) => String(subject.subjectId) === selectedSubject); const selectedName = selected?.subjectName || subjects.find((subject) => String(subject._id) === selectedSubject)?.name;
  const stats = [["Total subjects", summary.subjects ?? summary.totalSubjects ?? summary.totals?.subjects ?? 0], ["Total tasks", summary.tasks ?? summary.totalTasks ?? summary.totals?.tasks ?? 0], ["Pending", summary.pending ?? summary.pendingTasks ?? 0], ["Total attendance", `${Math.round(overall)}%`]];
  return <><div className="stats">{stats.map(([label, value]) => <div className="card" key={label}><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>)}</div><section className="card dashboard-attendance"><div className="section-title"><div><h2>Attendance by subject</h2><p className="muted">Choose an individual subject to view its attendance.</p></div><select className="attendance-select" value={selectedSubject} onChange={(event) => setSelectedSubject(event.target.value)}><option value="">Select a subject</option>{subjects.map((subject) => <option key={subject._id} value={subject._id}>{subject.name}</option>)}</select></div><div className="dashboard-attendance-result"><div><span className="stat-label">{selectedName || "Select a subject"}</span><strong>{selected ? `${Math.round(selected.percentage)}%` : "-"}</strong></div><span className="muted">{selected ? `${selected.present} present / ${selected.total} classes` : "Choose a subject from the dropdown to see its attendance."}</span></div></section><div className="grid-2"><section className="card"><div className="section-title"><h2>Priority focus</h2><Link to="/tasks">View all</Link></div>{summary.upcomingTasks?.length ? <div className="list">{summary.upcomingTasks.map((task) => <div className="list-item" key={task._id}><span>{task.title}</span><span className={`badge ${task.priority?.toLowerCase()}`}>{task.priority}</span></div>)}</div> : <div className="empty">No pending tasks.</div>}</section><section className="card dashboard-notes"><div className="section-title"><h2>Recent notes</h2><Link to="/notes">View all</Link></div>{summary.recentNotes?.length ? <div className="list">{summary.recentNotes.map((note) => <div className="list-item" key={note._id}><span>{note.title}</span><span className="muted">{new Date(note.updatedAt || note.createdAt).toLocaleDateString()}</span></div>)}</div> : <div className="empty">No notes yet.</div>}</section></div></>;
}