import { useMemo, useState } from "react";
import api from "../services/api";
import useFetch from "../hooks/useFetch";
import { messageOf } from "../utils/apiHelpers";
import Modal from "../components/Modal";

export default function Notes() {
  const { data, loading, error, reload } = useFetch("/notes"); const subjects = useFetch("/subjects"); const [search, setSearch] = useState(""); const [editing, setEditing] = useState(null); const [form, setForm] = useState({}); const [file, setFile] = useState(null); const [notice, setNotice] = useState("");
  const filtered = useMemo(() => data.filter((note) => `${note.title} ${note.content}`.toLowerCase().includes(search.toLowerCase())), [data, search]);
  const openPdf = async (id) => { const response = await api.get(`/notes/${id}/file`, { responseType: "blob" }); window.open(URL.createObjectURL(response.data), "_blank", "noopener,noreferrer"); };
  const save = async (event) => { event.preventDefault(); setNotice(""); if (file && (!file.name.toLowerCase().endsWith(".pdf") || file.type !== "application/pdf")) return setNotice("Only PDF files are allowed."); try { const body = new FormData(); Object.entries(form).forEach(([key, value]) => { if (!["_id", "createdAt", "updatedAt", "fileName", "filePath", "subjectId"].includes(key) && value !== undefined) body.append(key, value); }); const subjectId = typeof form.subjectId === "object" ? form.subjectId?._id : form.subjectId; if (subjectId) body.append("subjectId", subjectId); if (file) body.append("file", file); if (editing?._id) await api.put(`/notes/${editing._id}`, body); else await api.post("/notes", body); setEditing(null); setFile(null); reload(); } catch (requestError) { setNotice(messageOf(requestError)); } };
  const remove = async (id) => { if (window.confirm("Delete this note?")) { await api.delete(`/notes/${id}`); reload(); } };
  const startEdit = (note) => { setForm({ ...note, subjectId: note.subjectId?._id || note.subjectId || "" }); setFile(null); setNotice(""); setEditing(note); };
  return <><div className="toolbar"><div><h2>Notes</h2><p className="muted">Your quick revision library.</p></div><div className="actions"><input className="field search" placeholder="Search notes..." value={search} onChange={(event) => setSearch(event.target.value)} /><button className="primary" onClick={() => { setForm({}); setFile(null); setNotice(""); setEditing({}); }}>Add Note</button></div></div>{loading ? <div className="card empty">Loading...</div> : error ? <div className="error">{error}</div> : <div className="grid-2">{filtered.map((note) => <article className="card" key={note._id}><div className="section-title"><h2>{note.title}</h2><span className="badge">{note.subjectId?.name || "General"}</span></div><p className="note-content">{note.content}</p>{note.fileName && <button className="file-link" onClick={() => openPdf(note._id)}>Open PDF: {note.fileName}</button>}<div className="actions" style={{ marginTop: 16 }}><button className="secondary" onClick={() => startEdit(note)}>Edit</button><button className="danger" onClick={() => remove(note._id)}>Delete</button></div></article>)}{!filtered.length && <div className="card empty">No notes found.</div>}</div>}{editing !== null && <Modal title={editing._id ? "Edit note" : "Add note"} onClose={() => setEditing(null)}><form className="form" onSubmit={save}><label className="field">Title<input required value={form.title || ""} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label className="field">Subject<select value={form.subjectId || ""} onChange={(event) => setForm({ ...form, subjectId: event.target.value })}><option value="">General</option>{subjects.data.map((subject) => <option value={subject._id} key={subject._id}>{subject.name}</option>)}</select></label><label className="field">Content<textarea required={!file && !editing.fileName} value={form.content || ""} onChange={(event) => setForm({ ...form, content: event.target.value })} /></label><label className="field">PDF note<input type="file" accept=".pdf,application/pdf" onChange={(event) => setFile(event.target.files[0] || null)} />{file && <span className="muted">{file.name}</span>}{!file && editing.fileName && <span className="muted">Current file: {editing.fileName}</span>}</label>{notice && <div className="error">{notice}</div>}<button className="primary">Save note</button></form></Modal>}</>;
}