import { useState } from "react";
import api from "../services/api";
import { getData, messageOf } from "../utils/apiHelpers";

export default function Profile() {
  const [user, setUser] = useState(JSON.parse(localStorage.getItem("student_user") || "{}")); const [editing, setEditing] = useState(false); const [notice, setNotice] = useState("");
  const save = async (event) => { event.preventDefault(); setNotice(""); try { const data = getData(await api.put("/auth/profile", { name: user.name, course: user.course, semester: Number(user.semester), profilePicture: user.profilePicture || "" })); const updated = data.user || data; setUser(updated); localStorage.setItem("student_user", JSON.stringify(updated)); setEditing(false); setNotice("Profile updated."); } catch (requestError) { setNotice(messageOf(requestError)); } };
  const choosePicture = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return setNotice("Please choose an image file."); if (file.size > 2 * 1024 * 1024) return setNotice("Profile pictures must be smaller than 2 MB."); const reader = new FileReader(); reader.onload = () => setUser({ ...user, profilePicture: reader.result }); reader.readAsDataURL(file); };
  const initials = (user.name || "S").split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  const avatar = <div className="profile-avatar">{user.profilePicture ? <img src={user.profilePicture} alt={`${user.name}'s profile`} /> : initials}</div>;
  return <div className="profile-page"><section className="card profile-card"><div className="profile-hero">{avatar}<div><h2>{user.name || "Student"}</h2><p className="muted">{user.email || "No email added"}</p><span className="badge">{user.course || "Course not set"}{user.semester ? ` · Semester ${user.semester}` : ""}</span></div><button className="secondary profile-edit" onClick={() => { setEditing(true); setNotice(""); }}>Edit settings</button></div><div className="profile-details">{[["Full name", user.name], ["Email address", user.email], ["Course", user.course], ["Semester", user.semester]].map(([label, value]) => <div key={label}><span className="stat-label">{label}</span><strong>{value || "Not added"}</strong></div>)}</div></section>{notice && !editing && <div className="success profile-notice">{notice}</div>}{editing && <section className="card profile-settings"><div className="section-title"><div><h2>Edit profile</h2><p className="muted">Update your personal study details.</p></div><button className="ghost" type="button" onClick={() => setEditing(false)}>Cancel</button></div><form className="form" onSubmit={save}><label className="profile-picture-picker"><div className="profile-avatar small">{user.profilePicture ? <img src={user.profilePicture} alt="Selected profile preview" /> : initials}</div><span><strong>Profile picture</strong><small className="muted">JPG, PNG or GIF up to 2 MB</small><input type="file" accept="image/*" onChange={choosePicture} /></span></label><label className="field">Name<input required value={user.name || ""} onChange={(event) => setUser({ ...user, name: event.target.value })} /></label><label className="field">Email<input disabled value={user.email || ""} /></label><div className="form-grid"><label className="field">Course<input value={user.course || ""} onChange={(event) => setUser({ ...user, course: event.target.value })} /></label><label className="field">Semester<input type="number" min="1" max="12" value={user.semester || ""} onChange={(event) => setUser({ ...user, semester: event.target.value })} /></label></div>{notice && <div className="error">{notice}</div>}<button className="primary">Save changes</button></form></section>}</div>;
}